include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    avoid_private_typedef_functions: ignore
    cascade_invocations: ignore
    inference_failure_on_instance_creation: ignore
    one_member_abstracts: ignore


