name: clean_architecture_tdd_course
description: "A project implement clean architecture using TDD approach"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  # Functional programming thingies
  dartz: ^0.10.1
  # Network connectivity
  data_connection_checker_tv: ^0.3.5-nullsafety
  # Value equality
  equatable: ^2.0.5
  # Flutter sdk
  flutter:
    sdk: flutter
  # Bloc for state management
  flutter_bloc: ^8.1.6
  # Service locator
  get_it: ^7.7.0
  # Remote API
  http: ^1.2.2
  # Local cache
  shared_preferences: ^2.3.2
  # Code analysis
  very_good_analysis: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  
 
  assets:
    - assets/images/background.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 